### ISSUE TITLE
Contact Info Chunk?

### ISSUE THREAD

**Issue by lisaannerager** [cwolfsonseeley/discoappend#25]
Hey Caleb-

Possible to make a chunk that we could use in conjunction with basic Bio that would include phone and email?

Thanks!

**Comment by tarakc02** [comment]
@cwolfsonseeley  - maybe we can add this to the agenda for our next meeting? I am trying to remember if we were hesitant because of the fear they would be used for mailing lists or other bulk contacts (which was discussed at a staff meeting earlier this year). If not, then we should be able to add this to basic_bio without too much trouble; if so, we should get back to Lisa about alternative options.

**Comment by cwolfsonseeley** [comment]
After speaking with other analysts, there seems to be no reason for this chunk besides creating mailing lists, which we have been warned against. I'm closing this issue for now. If it becomes a need, I can reopen.
